version: '3'
services:
  blog:
    image: blog
    stdin_open: true
    ports:
      - "4000:4000"
    networks:
      - blog-app

  blog-backend:
    image: blog-backend
    ports:
      - "4001:4001"
    networks:
      - blog-app
networks:
  blog-app:
    driver: bridge